---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  # Group systems
  - cfn-outputs
  - instance-groups

- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - host-up

- name: Install packages necessary for installer
  hosts: nodes
  any_errors_fatal: true
  tasks:
  - when:
    - True | bool
    block:
    - name: Ensure openshift-ansible installer package deps are installed
      package:
        name: "{{ item }}"
        state: present
      with_items:
      - python-ipaddress
      when: item != ''
      register: result
      until: result is succeeded


- hosts: nodes
  gather_facts: yes
  become: yes
  vars_files:
  - vars/main.yaml
  roles:
  - non-atomic-docker-storage-setup
  - openshift-versions

- include: ../../../playbooks/prerequisite.yaml

- include: openshift-setup.yaml

- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
  - cfn-outputs
  - inventory-file-creation
