---
- name: "Create Route53 CNAME record for [master,registry,infra,logging,logging-ops,registry] external ELB endpoints"
  no_log: True
  route53:
    command: create
    overwrite: yes
    private_zone: no
    record: "{{ item.record }}.{{ r53zoneext.result.name }}"
    type: CNAME
    ttl: 300
    value: "{{ item.value.elb.dns_name }}"
    zone: "{{ r53zoneext.result.name }}"
  with_items:
    - record: 'master'
      value: "{{ elbextmaster }}"
    - record: 'infra'
      value: "{{ elbextinfra }}"
    - record: 'logging'
      value: "{{ elbextinfra }}"
    - record: 'logging-ops'
      value: "{{ elbextinfra }}"
    - record: 'registry'
      value: "{{ elbextinfra }}"
    - record: 'registry-console'
      value: "{{ elbextinfra }}"

- name: "Create Route53 CNAME records for [master,registry,infra,logging,logging-ops,registry] internal ELB endpoints"
  no_log: True
  route53:
    command: create
    overwrite: yes
    private_zone: yes
    record: "{{ item.record }}.{{ r53zoneint.result.name }}"
    type: CNAME
    ttl: 300
    value: "{{ item.value.elb.dns_name }}"
    zone: "{{ r53zoneint.result.name }}"
  with_items:
    - record: 'master'
      value: "{{ elbintmaster }}"

- name: "Create Route53 wildcard CNAME record (external)"
  route53:
    command: create
    overwrite: yes
    private_zone: no
    record: "*.apps.{{ clusterid }}.{{ domain }}"
    type: CNAME
    ttl: 300
    value: "{{ elbextinfra.elb.dns_name }}"
    zone: "{{ r53zoneext.result.name }}"
